import type { Metadata } from "next";
import { Providers } from "./Providers";

import Navigation from "@/components/Navbar/Navigation";
import localFont from "next/font/local";
import "./globals.css";

const publicSans = localFont({
    src: "../../public/assets/fonts/PublicSans-VariableFont_wght.ttf",
    variable: "--font-public-sans",
});

export const metadata: Metadata = {
    title: "Personal Finance App | Frontend Mentor",
    description: "Frontend Mentor challenge completed by Jon Deichmann. Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
            <body className={`min-h-screen font-[family-name:var(${publicSans.variable})] antialiased`}>
                <Providers>
                    <div className={`lg:h-dvh lg:flex lg:flex-row-reverse bg-[var(--beige-300)]`}>
                        {children}
                        <Navigation />
                    </div>
                </Providers>
            </body>
        </html>
    );
}
